---
- name: Generate a SSH key
  command : ssh-keygen -q -t rsa -C "" -N "" -f ~/.ssh/id_rsa
  args:
    creates: ~/.ssh/id_rsa
- name: Start the environment
  shell: |
    set -eux
    echo $PATH
    vl distro_list > virt-lightning.yaml
    vl up
    vl ansible_inventory > inventory
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
- name: Install Ansible
  package:
    name: ansible
  become: true
- name: Test the new VM
  shell: |
    ansible all -m shell -a "ping -c 1 google.ca" -i inventory
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
- name: List the VM
  command: "virsh -c {{ virt_lightning_qemu_uri }} list"
  register: list_vm
- name: Assert the VM is in the list
  assert:
    that:
      - "'centos' in list_vm.stdout"
- name: Destroy the environment
  shell: |
    vl down
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
- name: List the VM
  command: "virsh -c {{ virt_lightning_qemu_uri }} list"
  register: list_vm
- name: Assert the VM is not in the list
  assert:
    that:
      - "'centos' not in list_vm.stdout"
